# Configuration of the available formats

# Default formatting (if no format is specified)
default_format: "jj2"

# Allowed format (specified as file extension for instance 'xml')
allowed_formats: [ jj2, json, yml ]
